#!/bin/bash
drwxr-xr-x 2 root root 191 Feb 10 01:36 .                                                                                       

drwxr-xr-x 5 root root  90 Feb  9 04:43 ..                                                                                      

-rwxr--r-- 1 root root  16 Feb  8 17:59 0-current_working_directory                                                             

-rwxr--r-- 1 root root  15 Feb  9 21:48 1-listit                                                                                

-rwxr--r-- 1 root root  15 Feb  8 18:52 2-bring_me_home                                                                         

-rwxr--r-- 1 root root  18 Feb  9 21:59 3-listfiles                                                                             

-rwxr--r-- 1 root root  18 Feb 10 01:36 4-listmorefiles                                                                         

-rwxr--r-- 1 root root  20 Feb 10 01:16 5-listfilesdigitonly                                                                    

-rwxr--r-- 1 root root  42 Feb 10 01:33 6-firstdirectory                                                                        

-rw-r--r-- 1 root root  52 Feb  9 04:08 README.md  
